[package]
name = "chat-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
regex = "1"
reqwest = {version = "0.11.13", features=["json", "blocking"]}
serde_json = "1"
